### PR TITLE
Script injection fails for XHTML documents

### PR DESCRIPTION
**Pull request by yankee42**
The usage of document.write is not allowed in XHTML documents. Instead DOM functions are available in both XHTML and HTML documents.

### CODE REVIEW

**Comment by firstdoit** [comment]
@andineck LGTM

**Comment by andineck** [comment]
I think it might be good to test @HiroAgustin 's solution in IE see: #40 . If it works, I would prefer this solution (without DOM manipulation). What do you think?

**Comment by LongLiveCHIEF** [comment]
When is this going to be merged?

**Comment by yankee42** [comment]
Probably not at all because #59 solves the problem as well but is more elegant and also solves #40. However it does have a failing test (see this and the following comments: https://github.com/intesso/connect-livereload/issues/40#issuecomment-77589965)

**Pull request closed without merging**
